### ISSUE TITLE
[renameOnUpdate] Favorite or Stared actresses files cannot be renamed

### ISSUE THREAD

**Issue by fidofido300** [stashapp/CommunityScripts#105]
Stash is v0.17.2-45-g420c6fa9 (Latest dev)
renameOnUpdate is version: 2.3.3
When I try to rename file which contains favorite or stared actress I get...

2022-11-19 15:33:52 Error   [Plugin / renamerOnUpdate] KeyError: '80'
2022-11-19 15:33:52 Error   [Plugin / renamerOnUpdate]     perf_rating[str(perf['rating'])].append(perf['name'])
2022-11-19 15:33:52 Error   [Plugin / renamerOnUpdate]   File "D:\Media\Scrapers\Stash\plugins\renamerOnUpdate/renamerOnUpdate.py", line 506, in extract_info
2022-11-19 15:33:52 Error   [Plugin / renamerOnUpdate]     scene_information = extract_info(stash_scene, template)
2022-11-19 15:33:52 Error   [Plugin / renamerOnUpdate]   File "D:\Media\Scrapers\Stash\plugins\renamerOnUpdate/renamerOnUpdate.py", line 1054, in renamer
2022-11-19 15:33:52 Error   [Plugin / renamerOnUpdate]     renamer(FRAGMENT_SCENE_ID)
2022-11-19 15:33:52 Error   [Plugin / renamerOnUpdate]   File "D:\Media\Scrapers\Stash\plugins\renamerOnUpdate/renamerOnUpdate.py", line 1296, in <module>
2022-11-19 15:33:52 Error   [Plugin / renamerOnUpdate] Traceback (most recent call last):
2022-11-19 15:33:52 Error   [Plugin / renamerOnUpdate] main function error: '80'

When I remove stars and favorite flags, plugin works
Uploaded Config file
[renamerOnUpdate_config.zip](https://github.com/stashapp/CommunityScripts/files/10047121/renamerOnUpdate_config.zip)

**Comment by bnkai** [comment]
Closing as completed via #106
