### ISSUE TITLE
[renamerOnUpdate] Broken fields: $studio_family, $parent_studio, and $studio_hierarchy?

### ISSUE THREAD

**Issue by echo6ix** [stashapp/CommunityScripts#123]
@Belleyy I think I found another bug with renamerOnUpdate wrt studio templates and $studio_family and $parent_studio:

### $studio_family
```
studio_templates = {
    "ManyVids": "$studio_family/$studio.$date.$title{.$performer}"
}
```

$studio_family|$studio|$date|$title|Expected rename on update|Actual rename on update
---|---|---|---|---|---|
ManyVids|Blah|2022-01-01|Title|ManyVids/Blah.2022-01-01.Title|Blah/ManyVids2022-01-01.Title

### $parent_studio
```
studio_templates = {
    "ManyVids": "$parent_studio/$studio.$date.$title{.$performer}"
}
```

$parent_studio|$studio|$date|$title|Expected rename on update|Actual rename on update
---|---|---|---|---|---|
ManyVids|Blah|2022-01-01|Title|ManyVids/Blah.2022-01-01.Title|Blah/ManyVidsBlah.2022-01-01.Title

### $studio_hierarchy
```
studio_templates = {
    "ManyVids": "$studio_hierarchy/$studio.$date.$title{.$performer}"
}
```

$parent_studio|$studio|$date|$title|Expected rename on update|Actual rename on update
---|---|---|---|---|---|
ManyVids|Blah|2022-01-01|Title|ManyVids/Blah.2022-01-01.Title|ERROR

```ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate] main function error: replace() argument 2 must be str, not list
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate] Traceback (most recent call last):
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate]   File "/home/echo/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 1340, in <module>
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate]     renamer(FRAGMENT_SCENE_ID)
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate]   File "/home/echo/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 1107, in renamer
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate]     scene_information['new_filename'] = create_new_filename(scene_information, template["filename"])
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate]   File "/home/echo/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 782, in create_new_filename
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate]     new_filename = makeFilename(scene_info, template) + DUPLICATE_SUFFIX[scene_info['file_index']] + scene_info['file_extension']
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate]   File "/home/echo/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 751, in makeFilename
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate]     r, t = field_replacer(new_filename, scene_information)
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate]   File "/home/echo/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 745, in field_replacer
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate]     result = result.replace(f"${f}", replaced_word)
ERRO[2022-12-16 20:24:11] [Plugin / renamerOnUpdate] TypeError: replace() argument 2 must be str, not list
```

**Comment by echo6ix** [comment]
I think I had misunderstood how studio_template works. I'm closing this thread issue as I do not think it is a bug.
