### ISSUE TITLE
[RenamerOnUpdate] [Stash NFO Exporter for Kodi] Plugins no longer working after latest development channel update

### ISSUE THREAD

**Issue by MRobi1** [stashapp/CommunityScripts#186]
v0.23.1-23-g2b871810
Updated to latest this morning. Seems like both plugins have stopped working.

```
23-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate] ConnectionError: GraphQL query failed: 422 - b'{"errors":[{"message":"Cannot query field \\"oshash\\" on type \\"Scene\\".","locations":[{"line":9,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"checksum\\" on type \\"Scene\\".","locations":[{"line":10,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"rating\\" on type \\"Scene\\". Did you mean \\"rating100\\"?","locations":[{"line":13,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"rating\\" on type \\"Performer\\". Did you mean \\"rating100\\"?","locations":[{"line":51,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"oshash\\" on type \\"Scene\\".","locations":[{"line":9,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"checksum\\" on type \\"Scene\\".","locations":[{"line":10,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"rating\\" on type \\"Scene\\". Did you mean \\"rating100\\"?","locations":[{"line":13,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"rating\\" on type \\"Performer\\". Did you mean \\"rating100\\"?","locations":[{"line":51,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}'
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate]     raise ConnectionError(f"GraphQL query failed: {response.status_code} - {response.content}")
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate]   File "/root/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 97, in callGraphQL
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate]     result = callGraphQL(query, variables)
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate]   File "/root/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 154, in graphql_getScene
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate]     stash_scene = graphql_getScene(scene_id)
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate]   File "/root/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 1033, in renamer
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate]     renamer(FRAGMENT_SCENE_ID)
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate]   File "/root/.stash/plugins/renamerOnUpdate/renamerOnUpdate.py", line 1355, in <module>
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate] Traceback (most recent call last):
2023-10-18 10:27:28
Error   
[Plugin / renamerOnUpdate] main function error: GraphQL query failed: 422 - b'{"errors":[{"message":"Cannot query field \\"oshash\\" on type \\"Scene\\".","locations":[{"line":9,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"checksum\\" on type \\"Scene\\".","locations":[{"line":10,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"rating\\" on type \\"Scene\\". Did you mean \\"rating100\\"?","locations":[{"line":13,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"rating\\" on type \\"Performer\\". Did you mean \\"rating100\\"?","locations":[{"line":51,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"oshash\\" on type \\"Scene\\".","locations":[{"line":9,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"checksum\\" on type \\"Scene\\".","locations":[{"line":10,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"rating\\" on type \\"Scene\\". Did you mean \\"rating100\\"?","locations":[{"line":13,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"rating\\" on type \\"Performer\\". Did you mean \\"rating100\\"?","locations":[{"line":51,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}'
2023-10-18 10:27:28
Error   
Scene.Update.Post [Stash NFO Exporter for Kodi]: returned error: exit status 1
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]     . Variables: {'id': 9095}
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]     }
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]         weight
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]         hair_color
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]         death_date
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]         details
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]         rating
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]         }
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]             endpoint
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]             stash_id
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]         stash_ids {
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]         }
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]             ...SlimTagData
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]         tags {
2023-10-18 10:27:28
Error   
[Plugin / Stash NFO Exporter for Kodi]         movie_count
```

Reverting back to latest channel and v0.23.1 solves the issue.

**Comment by scruffynerf** [comment]
Yes, known issue, development has the breaking schema changes (very extensively changes).  Many scripts will break, so they'll need to be changed.  Hopefully the plugin improvement rolled out at the same time will help ease the pain.

The upcoming schema changes have been public for a while but nobody was being proactive.

RoU and SNEK will get full revamps soon.

**Comment by Tscherno** [comment]
I guess the same happened to the Stash-Plugin for Plex right? It still matches, but only gets Title and puts the date into the title.

**Comment by ofpcode** [comment]
@scruffynerf I started working through updates on RoU to work against my local development instance of Stash. Anything I can do to help with this plugin in particular? I'm happy to publish a pull request if it's helpful.

**Comment by MRobi1** [comment]
Now that v24 has hit the stable branch, is there a fix in the works for this or is the plugin unmaintained?

**Comment by scruffynerf** [comment]
> Now that v24 has hit the stable branch, is there a fix in the works for this or is the plugin unmaintained?

Working on v3.0, there are hacky shortcut fixes that basically remove items currently broken, but I'm not recommending those... I'm working on a rewrite that remove the use of sqlite direct access, and makes it easier to use, adds Plugin settings the new way, etc.

If you must have a quick fix, I can provide a link to someone's mod for it, but... At your own risk.

**Comment by gendi** [comment]
> If you must have a quick fix, I can provide a link to someone's mod for it, but... At your own risk.

Yes please, the link to a temporary fix would be great.

**Comment by Ashkaan** [comment]
v2.5 is working without issue for me.

**Comment by scruffynerf** [comment]
yes, RoU 2.5 is my stopgap fix until I get v3 out the door.
