### ISSUE TITLE
Plugins complaining about missing python packages

### ISSUE THREAD

**Issue by Humberd** [stashapp/CommunityScripts#222]
So after triggering and action it just logs an error and does nothing. It happens for all the plugins.
I run it on TrueNas.

```log
Plugin returned error: exit status 1
[Plugin / PHash Duplicate Tagger] ModuleNotFoundError: No module named 'stashapi'
[Plugin / PHash Duplicate Tagger]     import stashapi.log as log
[Plugin / PHash Duplicate Tagger]   File "/root/.stash/plugins/community/phashDuplicateTagger/config.py", line 1, in <module>
```

I tried running `pip install -r requirements` inside a container, but got the following info:

```log
error: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

```

**Comment by DogmaDragon** [comment]
There are 2 options here. You can either install it without setting up venv in which case the module will be lost once container is restarted or setting up venv and placing it in the mounted volume so it persists with the restarts. 

Option 1
```
pip install --user --break-system-packages stashapp-tools
```

Option 2
```
python -m venv /root/.stash/venv
source /root/.stash/venv/bin/activate
pip install stashapp-tools
```
`/root/.stash` is the default volume path of config set by example [docker-compose](https://github.com/stashapp/stash/blob/develop/docker/production/docker-compose.yml) so if you use a different one, change the path. 

---

There is talk about including the module as part of the Docker image, but as of now it's not included.

**Comment by Morfeel** [comment]
i have the same issue.
stash version v0.24.3
plugin: stashdb performer gallery
plugin version: 0.1-fbeb9bd 2/25/2024 3:11:40 PM
error: 
24-02-29 07:59:33
Error   
Plugin returned error: exit status 1
2024-02-29 07:59:33
Error   
[Plugin / stashdb performer gallery] ModuleNotFoundError: No module named 'stashapi'
2024-02-29 07:59:33
Error   
[Plugin / stashdb performer gallery]     import stashapi.log as log
2024-02-29 07:59:33
Error   
[Plugin / stashdb performer gallery]   File "/root/.stash/plugins/community/stashdb-performer-gallery/stashdb-performer-gallery.py", line 1, in <module>
2024-02-29 07:59:33
Error   
[Plugin / stashdb performer gallery] Traceback (most recent call last):
2024-02-29 07:59:31
Error   
Plugin returned error: exit status 1
2024-02-29 07:59:31
Error   
[Plugin / stashdb performer gallery] ModuleNotFoundError: No module named 'stashapi'

**Comment by Morfeel** [comment]
i tried install the requirements on the host, didn't work

**Comment by baldunderwear** [comment]
I went this route

python -m venv /root/.stash/venv
source /root/.stash/venv/bin/activate
pip install stashapp-tools

I have the install now in a permanent folder in the /root/.stash/venv folder, however even when I added that folder to my path statement the plugins still complain.

Any suggestions?

**Comment by Maista6969** [comment]
> I went this route
> 
> python -m venv /root/.stash/venv source /root/.stash/venv/bin/activate pip install stashapp-tools
> 
> I have the install now in a permanent folder in the /root/.stash/venv folder, however even when I added that folder to my path statement the plugins still complain.
> 
> Any suggestions?

What do you mean when you say you added that path to your "path statement"? If you set the environment variable `PYTHON_PATH` to that path it should work

You could also configure the Python path to `/root/.stash/venv/bin/python` in Stash itself so it uses the Python from your virtual environment, but that seems a little overkill when you're already Dockerized

Dogma's other suggestion of keeping the virtual environment outside of the container is a better idea 👍

**Comment by subzer011** [comment]
> There are 2 options here. You can either install it without setting up venv in which case the module will be lost once container is restarted or setting up venv and placing it in the mounted volume so it persists with the restarts.
> 
> Option 1
> 
> ```
> pip install --user --break-system-packages stashapp-tools
> ```
> 
> Option 2
> 
> ```
> python -m venv /root/.stash/venv
> source /root/.stash/venv/bin/activate
> pip install stashapp-tools
> ```
> 
> `/root/.stash` is the default volume path of config set by example [docker-compose](https://github.com/stashapp/stash/blob/develop/docker/production/docker-compose.yml) so if you use a different one, change the path.
> 
> There is talk about including the module as part of the Docker image, but as of now it's not included.

i've tried both options, neither worked. i ran the commands inside the container CLI via portainer and i still get errors in the log whenever i try any of the phash tasks. the phash plugin hasn't worked since the built-in plugin system was implemented. it use to work fine prior to the new system, when i updated/installed the plugin manually. this is the error i receive after running both option 1 and 2. i've also tried running each option individually, destroying the container and trying the other.

`024-03-10 15:43:38
Error   
Plugin returned error: exit status 1
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger] Exception: 422 Unprocessable Entity query failed. v0.25.0-7733
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]     raise Exception(error_msg)
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]   File "/root/.local/lib/python3.11/site-packages/stashapi/classes.py", line 279, in _handleGQLResponse
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]     return self._handleGQLResponse(response)
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]   File "/root/.local/lib/python3.11/site-packages/stashapi/classes.py", line 233, in _callGraphQL
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]     stash._callGraphQL(query, variables)
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]   File "/root/.stash/plugins/community/phashDuplicateTagger/phashDuplicateTagger.py", line 286, in generate_phash
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]     generate_phash()
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]   File "/root/.stash/plugins/community/phashDuplicateTagger/phashDuplicateTagger.py", line 62, in main
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]     main()
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger]   File "/root/.stash/plugins/community/phashDuplicateTagger/phashDuplicateTagger.py", line 293, in <module>
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger] Traceback (most recent call last):
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger] 422 Unprocessable Entity query failed. v0.25.0-7733
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger] 422 Unprocessable Entity GQL data response is null
2024-03-10 15:43:38
Error   
[Plugin / PHash Duplicate Tagger] GRAPHQL_VALIDATION_FAILED: must be defined ['variable', 'input']`

**Comment by stg-annon** [comment]
that is an error with PDT pending a fix with <https://github.com/stashapp/CommunityScripts/pull/276> you could also just run a generate task to generate PHASHs for files

**Comment by letraitplat** [comment]
Hello
Migrated stash from an old version, therefore went from some features handled by user scripts, to a plugin based.
For example, I wanted to use "stash performer favorite sync".

On my end, I have the same issue as OP, using latest stash on qnap / docker / portainer, but regarding pystashlib.
Unsure how it has been resolved.

When I go to portainer and try installing, I get same errors as mentioned above.

When I end up installing this way : 
pip install --user --break-system-packages pystashlib

I get this result : 
```
Requirement already satisfied: pystashlib in /root/.local/lib/python3.12/site-packages (0.5.0)
Requirement already satisfied: cloudscraper in /root/.local/lib/python3.12/site-packages (from pystashlib) (1.2.71)
Requirement already satisfied: pyyaml in /root/.local/lib/python3.12/site-packages (from pystashlib) (6.0.2)
Requirement already satisfied: python-dateutil in /root/.local/lib/python3.12/site-packages (from pystashlib) (2.9.0.post0)
Requirement already satisfied: requests in /usr/lib/python3.12/site-packages (from pystashlib) (2.32.3)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/lib/python3.12/site-packages (from cloudscraper->pystashlib) (3.1.4)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/lib/python3.12/site-packages (from cloudscraper->pystashlib) (1.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.12/site-packages (from requests->pystashlib) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.12/site-packages (from requests->pystashlib) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3.12/site-packages (from requests->pystashlib) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.12/site-packages (from requests->pystashlib) (2024.8.30)
Requirement already satisfied: six>=1.5 in /root/.local/lib/python3.12/site-packages (from python-dateutil->pystashlib) (1.17.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
```


Then now I get this error when I use the plugin : 
[Plugin / Stash Performer Audit Task Button] schema version mismatch. schema version is 72, expected 55


Any direction as to where to request help for those topics ? Thanks

**Comment by DogmaDragon** [comment]
@letraitplat that particualr plugin is broken due to the pystashlib library being outdated. https://discourse.stashapp.cc/t/stash-performer-audit-task-button/1731
