### ISSUE TITLE
Stash-watcher file not found???

### ISSUE THREAD

**Issue by apperrault** [stashapp/CommunityScripts#223]
hey y'all
I am trying to get stash-watcher running in a docker container and I am running into an issue.  The docker-compose is pretty straight forward and it looks to start to build, but then it throws an error.

```
01/18/2024
09:22:19 AM
d Using stash (v0.24.3-0) endpoint at http://stash:9999/graphql
01/18/2024
09:22:19 AM
Traceback (most recent call last):
01/18/2024
09:22:19 AM
  File "/usr/src/app/./watcher.py", line 240, in <module>
01/18/2024
09:22:19 AM
    main(stash, scanFlags, paths, extensions, timeout, pollInterval)
01/18/2024
09:22:19 AM
  File "/usr/src/app/./watcher.py", line 148, in main
01/18/2024
09:22:19 AM
    observer.start()
01/18/2024
09:22:19 AM
  File "/usr/local/lib/python3.11/site-packages/watchdog/observers/api.py", line 261, in start
01/18/2024
09:22:19 AM
    emitter.start()
01/18/2024
09:22:19 AM
  File "/usr/local/lib/python3.11/site-packages/watchdog/utils/__init__.py", line 92, in start
01/18/2024
09:22:19 AM
    self.on_thread_start()
01/18/2024
09:22:19 AM
  File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start
01/18/2024
09:22:19 AM
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
01/18/2024
09:22:19 AM
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01/18/2024
09:22:19 AM
  File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
01/18/2024
09:22:19 AM
    self._inotify = Inotify(path, recursive)
01/18/2024
09:22:19 AM
                    ^^^^^^^^^^^^^^^^^^^^^^^^
01/18/2024
09:22:19 AM
  File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 181, in __init__
01/18/2024
09:22:19 AM
    self._add_watch(path, event_mask)
01/18/2024
09:22:19 AM
  File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 416, in _add_watch
01/18/2024
09:22:19 AM
    Inotify._raise_error()
01/18/2024
09:22:19 AM
  File "/usr/local/lib/python3.11/site-packages/watchdog/observers/inotify_c.py", line 432, in _raise_error
01/18/2024
09:22:19 AM
    raise OSError(err, os.strerror(err))
01/18/2024
09:22:19 AM
FileNotFoundError: [Errno 2] No such file or directory`
```
here is the link to the whole log  https://pastebin.com/sL4JceYB

Anyone have any thoughts?

thanks

app

**Comment by David-Maisonave** [comment]
> Anyone have any thoughts?

You might want to try out [ChangeFileMonitor](https://github.com/David-Maisonave/Axter-Stash/tree/main/plugins/ChangeFileMonitor) plugin. It's similar to Stash-watcher, but as a plugin with improved features.
