### ISSUE TITLE
tag_graph Permission Error

### ISSUE THREAD

**Issue by binarygeek119** [stashapp/CommunityScripts#313]
is i run it inside the docker image with `python .\tag_graph.py -script` it works but inside of stash it doesnt

`INFO[2024-05-29 00:20:33] [Plugin / Tag Graph] generating graph...     
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph] Traceback (most recent call last): 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]   File "/config/plugins/CommunityScripts/tag_graph/tag_graph.py", line 272, in <module> 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]     plugin_init()       
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]   File "/config/plugins/CommunityScripts/tag_graph/tag_graph.py", line 216, in plugin_init 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]     generate_graph(stash_connection) 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]   File "/config/plugins/CommunityScripts/tag_graph/tag_graph.py", line 264, in generate_graph 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]     G.save_graph(save_path) 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]   File "/pip-install/install/pyvis/network.py", line 438, in save_graph 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]     self.write_html(name) 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]   File "/pip-install/install/pyvis/network.py", line 521, in write_html 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]     shutil.copytree(f"{os.path.dirname(__file__)}/templates/lib/bindings", "lib/bindings") 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]   File "/usr/lib/python3.11/shutil.py", line 561, in copytree 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks, 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]   File "/usr/lib/python3.11/shutil.py", line 459, in _copytree 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]     os.makedirs(dst, exist_ok=dirs_exist_ok) 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph]   File "<frozen os>", line 225, in makedirs 
ERRO[2024-05-29 00:20:33] [Plugin / Tag Graph] PermissionError: [Errno 13] Permission denied: 'lib/bindings' 
ERRO[2024-05-29 00:20:34] Plugin returned error: exit status 1  `

**Comment by stg-annon** [comment]
this version of the plugin is outdated use [this one](https://github.com/stg-annon/StashScripts/tree/main/plugins/tagGraph) for now until the community one is updated or removed

**Comment by feederbox826** [comment]
Reloacated to other repo #337
