### ISSUE TITLE
TPDBMarkers Issue - Exit Code 120

### ISSUE THREAD

**Issue by justaguyinaz** [stashapp/CommunityScripts#440]
Every time I run the Sync option from The Porn DB Markers section in tasks, it identifies all the scenes correctly, but then throws some errors and exits. This is what I see:

024-09-26 05:57:33
Error   
Plugin returned error: exit status 1
2024-09-26 05:57:33
Error   
[Plugin / The Porn DB Markers]                                                 ~~~~~^^^^^^^^^^
2024-09-26 05:57:33
Error   
[Plugin / The Porn DB Markers]     if settings["createMovieFromScene"] and len(scene["movies"]) ==0:
2024-09-26 05:57:33
Error   
[Plugin / The Porn DB Markers] KeyError: 'movies'
2024-09-26 05:57:33
Error   
[Plugin / The Porn DB Markers]     processScene(s)
2024-09-26 05:57:33
Error   
[Plugin / The Porn DB Markers]   File "/root/.stash/plugins/community/TPDBMarkers/tpdbMarkers.py", line 41, in processScene
2024-09-26 05:57:33
Error   
[Plugin / The Porn DB Markers]     processAll()
2024-09-26 05:57:33
Error   
[Plugin / The Porn DB Markers]   File "/root/.stash/plugins/community/TPDBMarkers/tpdbMarkers.py", line 100, in processAll
2024-09-26 05:57:33
Error   
[Plugin / The Porn DB Markers] Traceback (most recent call last):
2024-09-26 05:57:33
Error   
[Plugin / The Porn DB Markers]   File "/root/.stash/plugins/community/TPDBMarkers/tpdbMarkers.py", line 178, in <module>
2024-09-26 05:57:28
Info    
[Plugin / The Porn DB Markers] 329 scenes to submit.
2024-09-26 05:57:28
Info    
[Plugin / The Porn DB Markers] fetching data: 0 - 100 0.0%
2024-09-26 05:57:28
Info    
[Plugin / The Porn DB Markers] Getting scene count
2024-09-26 05:57:28
Info    
[Plugin / The Porn DB Markers] fetching data: 0 - 100 0.0%
2024-09-26 05:57:28
Info    
[Plugin / The Porn DB Markers] 329 scenes to submit.
2024-09-26 05:57:28
Info    
[Plugin / The Porn DB Markers] Getting scene count

@feederbox826

**Comment by feederbox826** [comment]
not my plugin, not sure why I'm getting pinged

**Comment by DogmaDragon** [comment]
@Tweeticoats is the author
