### ISSUE TITLE
Python Tools Installer - Installation error

### ISSUE THREAD

**Issue by lamyergeier** [stashapp/CommunityScripts#461]
Fedora 41, Wayland, Gnome 47

# Stash log

```log
time="2024-11-10 21:26:39" level=info msg="Installing package PythonToolsInstaller"
time="2024-11-10 21:26:39" level=info msg="Finished installing packages"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer] Traceback (most recent call last):"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]   File \"/mnt/Secure/stash/plugins/community/PythonToolsInstaller/PythonToolsInstaller.py\", line 63, in <module>"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]     main()"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]     ~~~~^^"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]   File \"/mnt/Secure/stash/plugins/community/PythonToolsInstaller/PythonToolsInstaller.py\", line 15, in main"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]     run(input, output)"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]     ~~~^^^^^^^^^^^^^^^"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]   File \"/mnt/Secure/stash/plugins/community/PythonToolsInstaller/PythonToolsInstaller.py\", line 38, in run"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]     get_download_py_stashapp_tools(PLUGIN_DIR)"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]   File \"/mnt/Secure/stash/plugins/community/PythonToolsInstaller/PythonToolsInstaller.py\", line 55, in get_download_py_stashapp_tools"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]     destination = shutil.copytree(src, org_packagedir,ignore_func,None,shutil.copy2,False,True)"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]   File \"/usr/lib64/python3.13/shutil.py\", line 593, in copytree"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]                      ignore=ignore, copy_function=copy_function,"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]                      ignore_dangling_symlinks=ignore_dangling_symlinks,"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]                      dirs_exist_ok=dirs_exist_ok)"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]   File \"/usr/lib64/python3.13/shutil.py\", line 491, in _copytree"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]     os.makedirs(dst, exist_ok=dirs_exist_ok)"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]   File \"<frozen os>\", line 217, in makedirs"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer]   File \"<frozen os>\", line 227, in makedirs"
time="2024-11-10 21:29:26" level=error msg="[Plugin / Python Tools Installer] PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.13'"
time="2024-11-10 21:29:26" level=error msg="Plugin returned error: exit status 1"
```

**Comment by ToniToba** [comment]
I have slightly the same issues but I am on a Windows Computer:

24-11-18 09:46:26
Error   
Plugin returned error: exit status 1
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer] FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                              ^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                              startupinfo)
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                              ^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                              cwd,
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     ...<4 lines>...
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                              ^^^^^^^^^^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                              # no special security
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]   File "C:\Users\Tobi\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1548, in _execute_child
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                         start_new_session, process_group)
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                         ^^^^^^^^^^^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                         gid, gids, uid, umask,
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     ...<5 lines>...
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                         ^^^^^^^^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]                         pass_fds, cwd, env,
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     self._execute_child(args, executable, preexec_fn, close_fds,
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]   File "C:\Users\Tobi\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1036, in __init__
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]          ~~~~~^^^^^^^^^^^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     with Popen(*popenargs, **kwargs) as process:
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]   File "C:\Users\Tobi\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 554, in run
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     subprocess.run([f"{used_dir}/venv/bin/pip", "install", "-r", abspath(f"{used_dir}/packages/stashtools.txt")],stdout=None)
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]   File "E:\stash\plugins\community\PythonToolsInstaller/PythonToolsInstaller.py", line 50, in get_download_py_stashapp_tools
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     get_download_py_stashapp_tools(PLUGIN_DIR)
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]   File "E:\stash\plugins\community\PythonToolsInstaller/PythonToolsInstaller.py", line 38, in run
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     ~~~^^^^^^^^^^^^^^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     run(input, output)
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]   File "E:\stash\plugins\community\PythonToolsInstaller/PythonToolsInstaller.py", line 15, in main
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     ~~~~^^
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]     main()
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer]   File "E:\stash\plugins\community\PythonToolsInstaller/PythonToolsInstaller.py", line 63, in <module>
2024-11-18 09:46:26
Error   
[Plugin / Python Tools Installer] Traceback (most recent call last):
