### ISSUE TITLE
[Sqlite_Renamer] TypeError: ProgressBar.__init__() got an unexpected keyword argument 'redirect_stdout'

### ISSUE THREAD

**Issue by JediMaster25** [stashapp/CommunityScripts#54]
```
❯ python Stash_Sqlite_Renamer.py
Database Path: /run/media/user/R/videos/stash/stash-go.sqlite
Python successfully connected to SQLite

Scenes numbers: 87863
Traceback (most recent call last):
  File "/run/media/user/R/videos/stash/scripts/Sqlite_Renamer/Stash_Sqlite_Renamer.py", line 299, in <module>
    edit_db("$studio $date $performer $title")
  File "/run/media/user/R/videos/stash/scripts/Sqlite_Renamer/Stash_Sqlite_Renamer.py", line 145, in edit_db
    progress = progressbar.ProgressBar(redirect_stdout=True).start(len(record))
TypeError: ProgressBar.__init__() got an unexpected keyword argument 'redirect_stdout'
```

**Comment by bnkai** [comment]
sqlite renamer is no longer maintained.
renamerOnUpdate now includes all functionality and is to be used instead
