### ISSUE TITLE
[Sqlite_Renamer] TypeError: logPrint() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by JediMaster25** [stashapp/CommunityScripts#57]
```
Traceback (most recent call last):
  File "/run/media/user/R/videos/stash/scripts/Sqlite_Renamer/Stash_Sqlite_Renamer.py", line 288, in <module>
    edit_db("$studio $date $performer $title")
  File "/run/media/user/R/videos/stash/scripts/Sqlite_Renamer/Stash_Sqlite_Renamer.py", line 201, in edit_db
    logPrint("Reduced filename to: {}", new_filename)
TypeError: logPrint() takes 1 positional argument but 2 were given
```

**Comment by bnkai** [comment]
sqlite renamer is no longer maintained.
renamerOnUpdate now includes all functionality and is to be used instead
